# Aether Configuration File
# Location: ~/.config/aether/aether_config.toml

# Global Settings
[settings]
quickSwitchEnabled = true  # Enable/disable all hotkeys globally

# Application Configurations
[[apps]]
# Basic app info
appName = "Terminal"
bundleID = "com.apple.Terminal"
enabled = true
customLaunchPath = "/Applications/Terminal.app"  # Optional: custom path to the application

# Hotkey settings
hotkeyKey = "T"  # Single character key
hotkeyModifiers = ["command", "option"]  # Available: command, option, control, shift

# Window behavior settings
windowCycleMethod = "next"  # Available: "next", "stack", "minimize"
windowRestoreLayout = true  # Remember and restore window positions
windowGroupBySpaces = true  # Only cycle through windows in current space
windowFollowFocus = true    # Switch spaces if window is on different space

[[apps]]
appName = "Safari"
bundleID = "com.apple.Safari"
enabled = true
hotkeyKey = "S"
hotkeyModifiers = ["command", "option"]
windowCycleMethod = "stack"
windowRestoreLayout = false
windowGroupBySpaces = false
windowFollowFocus = false

[[apps]]
appName = "Visual Studio Code"
bundleID = "com.microsoft.VSCode"
enabled = true
hotkeyKey = "V"
hotkeyModifiers = ["command", "option", "shift"]  # Example of using three modifiers
windowCycleMethod = "next"
windowRestoreLayout = true
windowGroupBySpaces = true
windowFollowFocus = true

[[apps]]
appName = "Slack"
bundleID = "com.slack.Slack"
enabled = true
hotkeyKey = "L"
hotkeyModifiers = ["command", "control"]  # Example of different modifier combination
windowCycleMethod = "minimize"  # Example of using minimize instead of cycling
windowRestoreLayout = false
windowGroupBySpaces = false
windowFollowFocus = false

[[apps]]
appName = "Google Chrome"
bundleID = "com.google.Chrome"
enabled = true
hotkeyKey = "C"
hotkeyModifiers = ["command", "option"]
windowCycleMethod = "next"
windowRestoreLayout = true
windowGroupBySpaces = true
windowFollowFocus = true

[[apps]]
appName = "Finder"
bundleID = "com.apple.finder"
enabled = true
hotkeyKey = "F"
hotkeyModifiers = ["command", "option"]
windowCycleMethod = "stack"
windowRestoreLayout = true
windowGroupBySpaces = false
windowFollowFocus = true

# Configuration Notes:
# 1. Each application must have a unique hotkey combination
# 2. Available modifier keys: command, option, control, shift
# 3. Window cycle methods:
#    - "next": Cycle through windows in order
#    - "stack": Cycle based on most recently used
#    - "minimize": Minimize the current window
# 4. Window behavior options:
#    - windowRestoreLayout: Remember window positions
#    - windowGroupBySpaces: Only cycle through windows in current space
#    - windowFollowFocus: Follow focus across spaces
# 5. All boolean values use true/false (lowercase)
# 6. Strings must be in "quotes" 